language: python
sudo: false
install:
- pip install Pygments
- curl -Lo /tmp/texlive.tar.gz https://github.com/yihui/ubuntu-bin/releases/download/latest/texlive.tar.gz
- tar xzf /tmp/texlive.tar.gz -C ~
- export PATH=/$HOME/texlive/bin/x86_64-linux:$PATH
- tlmgr update --self
- tlmgr install algorithmicx esint babel-italian hyphen-italian minted ifplatform
- curl "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh"
  -o dropbox_uploader.sh
- chmod +x dropbox_uploader.sh
- '[ "$TRAVIS_SECURE_ENV_VARS" == "false" ] || openssl aes-256-cbc -K $encrypted_3d69c5542c5a_key -iv $encrypted_3d69c5542c5a_iv
  -in .dropbox_uploader.enc -out ~/.dropbox_uploader -d'
script:
- xelatex -synctex=1 -shell-escape -interaction=nonstopmode tesi.tex
- bibtex _build/tesi
- xelatex -synctex=1 -shell-escape -interaction=nonstopmode tesi.tex
- xelatex -synctex=1 -shell-escape -interaction=nonstopmode tesi.tex
after_success:
- ./dropbox_uploader.sh upload tesi.pdf ${FOLDER}/${FILENAME}.pdf
