language: r
sudo: false
before_install:
- '[ "$TRAVIS_SECURE_ENV_VARS" == "false" ] || openssl aes-256-cbc -K $encrypted_3d69c5542c5a_key -iv $encrypted_3d69c5542c5a_iv
  -in .dropbox_uploader.enc -out ~/.dropbox_uploader -d'
- tlmgr install algorithmicx babel-italian esint
- curl "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh"
  -o dropbox_uploader.sh
- chmod +x dropbox_uploader.sh
script:
- mkdir _build
- pdflatex -output-directory _build tesi.tex
- cp bibliografia.bib _build
- bibtex _build/tesi
- pdflatex -output-directory _build tesi.tex
- pdflatex -output-directory _build tesi.tex
after_success:
- ./dropbox_uploader.sh upload _build/tesi.pdf ${FOLDER}/${FILENAME}.pdf
