language: ruby
install:
- curl -Lo /tmp/texlive.tar.gz https://github.com/yihui/ubuntu-bin/releases/download/latest/texlive.tar.gz
- tar xzf /tmp/texlive.tar.gz -C ~
- export PATH=/$HOME/texlive/bin/x86_64-linux:$PATH
- tlmgr update --self
- tlmgr install algorithmicx babel-italian esint
- fmtutil --all
- curl "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh"
  -o dropbox_uploader.sh
- chmod +x dropbox_uploader.sh
- '[ "$TRAVIS_SECURE_ENV_VARS" == "false" ] || openssl aes-256-cbc -K $encrypted_3d69c5542c5a_key -iv $encrypted_3d69c5542c5a_iv
  -in .dropbox_uploader.enc -out ~/.dropbox_uploader -d'
script:
- mkdir _build
- pdflatex -output-directory _build tesi.tex
- cp bibliografia.bib _build
- bibtex _build/tesi
- pdflatex -output-directory _build tesi.tex
- pdflatex -output-directory _build tesi.tex
after_success:
- ./dropbox_uploader.sh upload _build/tesi.pdf ${FOLDER}/${FILENAME}.pdf
